Repository srakhe/olympics, pull requests merged in 2022-03, with the labels that each got.

#6 Games list scraper
  scripts/scrapers/olympic/country_codes.py
  scripts/scrapers/olympic/country_codes_scraper.py
  scripts/scrapers/olympic/data/countries.html
  scripts/scrapers/olympic/data/games.html
  scripts/scrapers/olympic/data/games/summer.csv
  scripts/scrapers/olympic/data/games/winter.csv
  scripts/scrapers/olympic/games_list.py
  scripts/scrapers/olympic/main.py
  scripts/scrapers/olympic/scraper.py
  scripts/scrapers/scrape_utils.py
  scripts/scrapers/utils.py
Labels: enhancement

#8 Sports cost
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/LICENSE
  scripts/scrapers/olympics-economy/data/olympic_cost.csv
  scripts/scrapers/olympics-economy/data/olympic_cost.html
  scripts/scrapers/olympics-economy/main.py
Labels: enhancement

#11 Final update to olympic scraper.
  LICENSE
  README.md
  scripts/scrapers/olympic/data/medals.csv
  scripts/scrapers/olympic/data/medals.html
  scripts/scrapers/olympic/main.py
  scripts/scrapers/olympic/medals_counts.py
Labels: enhancement

#14 Sports cost
  scripts/analysis/sentiment/data/tokyo_after.csv
  scripts/analysis/sentiment/data/tokyo_before.csv
  scripts/analysis/sentiment/sentiment_analysis_tokyo.py
Labels: enhancement

#18 Merging dev to main
  research/analysis/domain_eda.ipynb
  research/papers/economic_impact/1.pdf
  research/papers/economic_impact/2.pdf
  research/papers/economic_impact/3.pdf
  research/papers/economic_impact/4.pdf
  research/papers/economic_impact/sydney.pdf
  research/papers/economic_impact/to_host_or_not.pdf
  research/papers/olympic_fact_file_2014.pdf
  research/papers/sentiment_analysis/sentiment_olympics.pdf
Labels: documentation

#19 add git attr to fix language in repo
  .gitattributes
Labels: bug
